version: "3.8"
services:
  mongodb-deepak:
    container_name: mongodb-deepak
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=deepak
      - MONGO_INITDB_ROOT_PASSWORD=deepak123
    volumes:
      - /home/ishika/Database:/data/db
  hms-api-gateway:
    image: hms-api-gateway
    networks:
      - my-hms-network
    ports:
      - "7000:7000"
    volumes:
      - /home/ishika/Projects/HMS/hms-api-gateway/.env:/app/.env

  hms-user-access:
    image: hms-user-access
    networks:
      - my-hms-network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "8000:8000"
    volumes:
      - /home/ishika/Projects/HMS/hms-user-access/.env:/app/.env

networks:
  my-hms-network:
    driver: bridge
